name: Documentation issue
description: Report a problem with the documentation
body:
  - type: checkboxes
    attributes:
      label: Support guidelines
      description: Please read the support guidelines before proceeding.
      options:
        - label: I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
          required: true
  - type: checkboxes
    attributes:
      label: Use of AI
      description: AI agents like Claude and CoPilot are not reliable tools. Do not use them.
      options:
        - label: I'm a real person and wrote this bug without assistance from AI.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Please provide a brief description of the issue in 1-2 sentences.
      placeholder: Please DO NOT use AI / LLM to fill this form.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Please provide any additional information that seems useful.
      placeholder: Please DO NOT use AI / LLM to fill this form.
